function [path] = pathplanner(m1,m2,l,g,N2,inputConstraint)
addpath(genpath('C:\Users\filma90\Documents\Research\stochastic-optimization\model in yop\yop'))
addpath(genpath('C:\Users\filma90\Documents\MATLAB\casadi-v3.5.5'))

%% Cart-pendulum model
sys = YopSystem('states', 4, 'controls', 1);

% Symbolic variables
t = sys.t;
x = sys.x;
u = sys.u;

g = 9.8067;
 
% differential equation
xdot = [1;
        (l*m2*sin(x(3))*(x(4))^2+u(1)+m2*g*cos(x(3))*sin(x(3)))/(m1+m2*(1-(cos(x(3)))^2));
        x(4);
        -(l*m2*cos(x(3))*sin(x(3))*(x(4))^2+u(1)*cos(x(3))+(m1+m2)*g*sin(x(3)))/(l*m1+l*m2*(1-(cos(x(3)))^2))];

sys.set('ode',xdot)

% Formulate the optimal control problem
ocp = YopOcp();
ocp.min({t_f(x(1))})
ocp.st(... 
    'systems', sys, ...
    ... % Initial conditions
    {  0 '==' t_0(x(1))}, ...
    {  0 '==' t_0(t)}, ...
    {  0 '==' t_0(x(2))}, ...
    {  0 '==' t_0(x(3))}, ...
    {  0 '==' t_0(x(4))}, ...
    ... % Terminal conditions
    {  3 '==' t_f(t)}, ...    
    {  0 '==' t_f(x(2))}, ...
    {  0 '==' t_f(x(3))}, ...
    {  0 '==' t_f(x(4))}, ...
    ... % Constraints
    {  0 '<=' x(1) '<=' inf}, ...
    {  0 '<=' x(2) '<=' inf}, ...
    {  -0.15 '<=' x(3) '<=' 0.15}, ...
    { inputConstraint(1) '<=' u(1) '<=' inputConstraint(2)});

N1 = 10;

 sol = ocp.solve( ...
     'controlIntervals', N1, ...
     'polynomialDegree', 1);

 sol = ocp.solve( ...
     'controlIntervals', N2, ...
     'polynomialDegree', 1, ...
     'initialGuess',YopWarmstart(sol,sys,N2));
 
path = struct('Independent',sol.NumericalResults.Independent,'State',sol.NumericalResults.State,'Input',sol.NumericalResults.Control);

end

